# Generated by Django 4.2.4 on 2023-08-24 20:14

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.ImageField(
                null=True, upload_to=user.models.user_image_file_path
            ),
        ),
    ]
